### ISSUE TITLE
Herobanner JS functionality

### ISSUE THREAD

**Issue by JrSchoolAccount** [JrSchoolAccount/Group-Assignment2-Cinema-Project#13]
Add JS to make a herobanner slideshow with popular movies.

PR: #54

# Fix
PR: #59

**Comment by NelsonTheBrave** [comment]
Tested, looks good except for comment below

**Comment by NelsonTheBrave** [comment]
Something doesn't work between import of showSlides and the code in main.js to show header and footer on several sides

**Comment by JrSchoolAccount** [comment]
@NelsonTheBrave Fixed it by adding type="module" to the other sites :)

**Comment by NelsonTheBrave** [comment]
yes, seems to work fine now!
