### ISSUE TITLE
Herobanner CSS & animation

### ISSUE THREAD

**Issue by JrSchoolAccount** [JrSchoolAccount/Group-Assignment2-Cinema-Project#14]
Style the herobanner with CSS and animation to make it look better and smoother.

As a general user, i want to se popular movies in a good looking slideshow.

PR: #55

**Comment by JrSchoolAccount** [comment]
https://github.com/JrSchoolAccount/Group-Assignment2-Cinema-Project/assets/144328779/6d5424d6-00e4-4b4c-8339-a3c450630f19

**Comment by NelsonTheBrave** [comment]
Fixes to previous card with herobanner js need to be done before this can be properly tested

**Comment by NelsonTheBrave** [comment]
ok, looks great :)
