### ISSUE TITLE
göra nåt coolt

### ISSUE THREAD

**Issue by FelixHultman** [JrSchoolAccount/Group-Assignment2-Cinema-Project#2]

**Comment by FelixHultman** [comment]
nu händer det saker

**Comment by NelsonTheBrave** [comment]
What kind of cool thing are you planning to do?

**Comment by FelixHultman** [comment]
> What kind of cool thing are you planning to do?

planning on removing it, thought i already had done that ^^

**Comment by NelsonTheBrave** [comment]
No, it's impossible to remove.... this will live forever now moahahaha

**Comment by NelsonTheBrave** [comment]
Actually, I think you only removed it from the sprint preparation project but it was still part of the repo so I found it under the headline "issues" for the repo.... And now I fucked around with you and re-added it to the project for some random reason!
