### ISSUE TITLE
add a FAQ

### ISSUE THREAD

**Issue by FelixHultman** [JrSchoolAccount/Group-Assignment2-Cinema-Project#21]
Add an icon somewhere on the site that show faq

**Comment by FelixHultman** [comment]
![Image](https://github.com/JrSchoolAccount/Group-Assignment2-Cinema-Project/assets/145000258/092c82df-97cd-40b9-8e49-de99fbaa3c65)

something like that

**Comment by JrSchoolAccount** [comment]
Tested and working 👍
