### ISSUE TITLE
Add movie data to the movie-database

### ISSUE THREAD

**Issue by FelixHultman** [JrSchoolAccount/Group-Assignment2-Cinema-Project#23]
movieTitle:
movieGenre:
MovieLength:
movieAgeLimit:
movieCover :

**Comment by JrSchoolAccount** [comment]
I found this page where you can generate posters for the movies :)

https://www.movierankings.net/random

**Comment by FelixHultman** [comment]
> I found this page where you can generate posters for the movies :)
> 
> https://www.movierankings.net/random

cant find where to do that?
