### ISSUE TITLE
Styling of the main page

### ISSUE THREAD

**Issue by rl-86** [JrSchoolAccount/Group-Assignment2-Cinema-Project#29]
## Color Palette
![Image](https://github.com/JrSchoolAccount/Group-Assignment2-Cinema-Project/assets/144328779/5402ddd1-b935-4fff-adf5-60c282fafc3d)

## Description
Implement the main style of the page using the above color palette.
With the below screenshot as inspiration.

## Screenshot
![Image](https://github.com/JrSchoolAccount/Group-Assignment2-Cinema-Project/assets/144328779/d9d08075-19b2-4fdb-a68c-9900f999b0d8)

**Comment by rl-86** [comment]
Made PR: https://github.com/JrSchoolAccount/Group-Assignment2-Cinema-Project/pull/63

**Comment by MasakiShiraishi** [comment]
It's great. Someone do a test and seems be no problems, so I moved it to Done.
