### ISSUE TITLE
As a general user, I would like the SNS icon to be displayed somewhere on the page.

### ISSUE THREAD

**Issue by MasakiShiraishi** [JrSchoolAccount/Group-Assignment2-Cinema-Project#40]

**Comment by MasakiShiraishi** [comment]
I added 4 SNS icons at the bottom right of the header.

**Comment by NelsonTheBrave** [comment]
Looks good

**Comment by MasakiShiraishi** [comment]
I created a new PR: Sns icons #56 because of having fixed the my mistake.

**Comment by JrSchoolAccount** [comment]
Failed the test :(
The icons looks good, but the footer does not 😅 

# screenshot
![Image](https://github.com/JrSchoolAccount/Group-Assignment2-Cinema-Project/assets/144328779/cb4ce86d-932a-44a1-82f6-7f257d3409ce)

**Comment by MasakiShiraishi** [comment]
Pull request is here:
Sns icons #60 

I adjusted and fixed to header postion and this time, it seems to be good.




screenshot

![Image](https://github.com/JrSchoolAccount/Group-Assignment2-Cinema-Project/assets/112933577/1a0a24fa-311d-41c0-92dc-43d5c93d4587)

**Comment by JrSchoolAccount** [comment]
Tested and working 👍
