### ISSUE TITLE
Meta tags to HTML

### ISSUE THREAD

**Issue by MasakiShiraishi** [JrSchoolAccount/Group-Assignment2-Cinema-Project#53]

**Comment by MasakiShiraishi** [comment]
As a developer(?) I want the site to have good meta tags so that the site is shown well as a link in e.g. social media

**Comment by MasakiShiraishi** [comment]
Pull request finns att kolla på här:
adding meta-tag to html-files #57

**Comment by NelsonTheBrave** [comment]
looks like it works well, tested
